-- SELECT ROUND(AVG(RENTAL_RATE),3)  FROM FILM;

-- SELECT COUNT(*) FROM FILM
-- WHERE TITLE LIKE 'C%';

-- SELECT MAX (LENGTH) FROM FILM
-- WHERE RENTAL_RATE = 0.99;

-- SELECT COUNT(REPLACEMENT_COST) FROM FILM
-- WHERE LENGTH >= 150;